apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{NAME}"
spec:
  template:
    metadata:
      labels:
        component: "{NAME}"
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: service
        image: eu.gcr.io/playnet-gce/{NAME}:dev
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret
              key: discord-token
        - name: DISCORD_GUILD
          valueFrom:
            secretKeyRef:
              name: secret
              key: discord-guild
        - name: DEBUG
          value: "true"
        - name: SENTRYDSN
          value: ""
        - name: IS_PROD
          value: "false"
        - name: LOCAL
          value: "true"
        - name: METRICS
          value: ":8080"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: secret

