apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
    component: secret
type: Opaque
data:
  discord-token: "{{ "DISCORD_TOKEN" | env | base64 }}"
  discord-guild: "{{ "DISCORD_GUILD" | env | base64 }}"